"""feat: add user extra fields

Revision ID: 56e3549981aa
Revises: a7f2d1e5d135
Create Date: 2026-01-21 19:34:07.416063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56e3549981aa'
down_revision: Union[str, Sequence[str], None] = 'a7f2d1e5d135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('student_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('major', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('instagram_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('mbti', sa.String(length=10), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'mbti')
    op.drop_column('users', 'instagram_id')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'major')
    op.drop_column('users', 'student_id')
    # ### end Alembic commands ###
