"""Initial schema

Revision ID: 86a689aa902d
Revises: 44f2b8fec6e0
Create Date: 2026-01-17 20:19:54.216668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86a689aa902d'
down_revision: Union[str, Sequence[str], None] = '44f2b8fec6e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('room_type', sa.Enum('GENERAL', 'CUSTOM', 'BUILDING', name='roomtype'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('owner_type', sa.Enum('USER', 'TEAM', 'SYSTEM', name='ownertype'), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rooms_is_public', 'rooms', ['is_public'], unique=False)
    op.create_index('idx_rooms_owner', 'rooms', ['owner_type', 'owner_id'], unique=False)
    op.create_index('idx_rooms_room_type', 'rooms', ['room_type'], unique=False)
    op.create_table('room_objects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('object_asset_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_room_objects_asset', 'room_objects', ['object_asset_id'], unique=False)
    op.create_index('idx_room_objects_room_id', 'room_objects', ['room_id'], unique=False)
    op.create_index('uq_room_objects_position', 'room_objects', ['room_id', 'x', 'y'], unique=True)
    op.create_table('room_portals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('from_room_id', sa.BigInteger(), nullable=False),
    sa.Column('from_x', sa.Integer(), nullable=False),
    sa.Column('from_y', sa.Integer(), nullable=False),
    sa.Column('to_room_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['from_room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['to_room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_room_portals_from_position', 'room_portals', ['from_room_id', 'from_x', 'from_y'], unique=False)
    op.create_index('idx_room_portals_from_room', 'room_portals', ['from_room_id'], unique=False)
    op.create_index('idx_room_portals_to_room', 'room_portals', ['to_room_id'], unique=False)
    op.create_table('room_tiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('tile_asset_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_room_tiles_asset', 'room_tiles', ['tile_asset_id'], unique=False)
    op.create_index('idx_room_tiles_room_id', 'room_tiles', ['room_id'], unique=False)
    op.create_index('uq_room_tiles_position', 'room_tiles', ['room_id', 'x', 'y'], unique=True)
    op.create_table('friends',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('friend_user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'BLOCKED', name='friendstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['friend_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_friends_friend_user_id', 'friends', ['friend_user_id'], unique=False)
    op.create_index('idx_friends_user_id', 'friends', ['user_id'], unique=False)
    op.create_index('uq_friends_pair', 'friends', ['user_id', 'friend_user_id'], unique=True)
    op.create_table('room_roles',
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'EDITOR', 'VISITOR', name='roomroletype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'user_id')
    )
    op.create_index('idx_room_roles_user_id', 'room_roles', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_teams_owner_user_id', 'teams', ['owner_user_id'], unique=False)
    op.add_column('users', sa.Column('nickname', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('real_name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.Enum('GOOGLE', 'LOCAL', name='authprovider'), nullable=False))
    op.add_column('users', sa.Column('rc', sa.Enum('Torrey', 'JangGiRyeo', 'Kuyper', 'SonYangWon', 'Philadelphos', 'Carmichael', name='rc'), nullable=False))
    op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='userstatus'), nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_room_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('last_room_x', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_room_y', sa.Integer(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('idx_users_auth_provider', 'users', ['auth_provider'], unique=False)
    op.create_index('idx_users_last_room_id', 'users', ['last_room_id'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_foreign_key(None, 'users', 'rooms', ['last_room_id'], ['id'])
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('idx_users_last_room_id', table_name='users')
    op.drop_index('idx_users_auth_provider', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'last_room_y')
    op.drop_column('users', 'last_room_x')
    op.drop_column('users', 'last_room_id')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'status')
    op.drop_column('users', 'rc')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'real_name')
    op.drop_column('users', 'nickname')
    op.drop_index('idx_teams_owner_user_id', table_name='teams')
    op.drop_table('teams')
    op.drop_index('idx_room_roles_user_id', table_name='room_roles')
    op.drop_table('room_roles')
    op.drop_index('uq_friends_pair', table_name='friends')
    op.drop_index('idx_friends_user_id', table_name='friends')
    op.drop_index('idx_friends_friend_user_id', table_name='friends')
    op.drop_table('friends')
    op.drop_index('uq_room_tiles_position', table_name='room_tiles')
    op.drop_index('idx_room_tiles_room_id', table_name='room_tiles')
    op.drop_index('idx_room_tiles_asset', table_name='room_tiles')
    op.drop_table('room_tiles')
    op.drop_index('idx_room_portals_to_room', table_name='room_portals')
    op.drop_index('idx_room_portals_from_room', table_name='room_portals')
    op.drop_index('idx_room_portals_from_position', table_name='room_portals')
    op.drop_table('room_portals')
    op.drop_index('uq_room_objects_position', table_name='room_objects')
    op.drop_index('idx_room_objects_room_id', table_name='room_objects')
    op.drop_index('idx_room_objects_asset', table_name='room_objects')
    op.drop_table('room_objects')
    op.drop_index('idx_rooms_room_type', table_name='rooms')
    op.drop_index('idx_rooms_owner', table_name='rooms')
    op.drop_index('idx_rooms_is_public', table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
