"""AuthProvider Kakao, Naver Enum added

Revision ID: a7f2d1e5d135
Revises: 618f6192ec6a
Create Date: 2026-01-17 20:44:58.116633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f2d1e5d135'
down_revision: Union[str, Sequence[str], None] = '618f6192ec6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
