"""Add nickname field to Avatar model

Revision ID: c8648bda15a5
Revises: a13d5a3d507a
Create Date: 2026-03-14 17:22:26.886127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8648bda15a5'
down_revision: Union[str, Sequence[str], None] = 'a13d5a3d507a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatars', sa.Column('nickname', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avatars', 'nickname')
    # ### end Alembic commands ###
