"""initial schema with all features

Revision ID: e3136d1ae3bd
Revises: 
Create Date: 2026-01-22 16:16:27.388684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3136d1ae3bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('room_type', sa.Enum('GENERAL', 'CUSTOM', 'BUILDING', name='roomtype'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('owner_type', sa.Enum('USER', 'TEAM', 'SYSTEM', name='ownertype'), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rooms_is_public', 'rooms', ['is_public'], unique=False)
    op.create_index('idx_rooms_owner', 'rooms', ['owner_type', 'owner_id'], unique=False)
    op.create_index('idx_rooms_room_type', 'rooms', ['room_type'], unique=False)
    op.create_table('room_objects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('object_asset_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_room_objects_asset', 'room_objects', ['object_asset_id'], unique=False)
    op.create_index('idx_room_objects_room_id', 'room_objects', ['room_id'], unique=False)
    op.create_index('uq_room_objects_position', 'room_objects', ['room_id', 'x', 'y'], unique=True)
    op.create_table('room_portals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('from_room_id', sa.BigInteger(), nullable=False),
    sa.Column('from_x', sa.Integer(), nullable=False),
    sa.Column('from_y', sa.Integer(), nullable=False),
    sa.Column('to_room_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['from_room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['to_room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_room_portals_from_position', 'room_portals', ['from_room_id', 'from_x', 'from_y'], unique=False)
    op.create_index('idx_room_portals_from_room', 'room_portals', ['from_room_id'], unique=False)
    op.create_index('idx_room_portals_to_room', 'room_portals', ['to_room_id'], unique=False)
    op.create_table('room_tiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('tile_asset_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_room_tiles_asset', 'room_tiles', ['tile_asset_id'], unique=False)
    op.create_index('idx_room_tiles_room_id', 'room_tiles', ['room_id'], unique=False)
    op.create_index('uq_room_tiles_position', 'room_tiles', ['room_id', 'x', 'y'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('real_name', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.Enum('GOOGLE', 'NAVER', 'KAKAO', 'LOCAL', name='authprovider'), nullable=False),
    sa.Column('rc', sa.Enum('Torrey', 'JangGiRyeo', 'Kuyper', 'SonYangWon', 'Philadelphos', 'Carmichael', name='rc'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', 'NEW', 'GUEST', name='userstatus'), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_room_id', sa.BigInteger(), nullable=True),
    sa.Column('last_room_x', sa.Integer(), nullable=True),
    sa.Column('last_room_y', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('instagram_id', sa.String(length=100), nullable=True),
    sa.Column('mbti', sa.Enum('ISTJ', 'ISFJ', 'INFJ', 'INTJ', 'ISTP', 'ISFP', 'INFP', 'INTP', 'ESTP', 'ESFP', 'ENFP', 'ENTP', 'ESTJ', 'ESFJ', 'ENFJ', 'ENTJ', name='mbti'), nullable=True),
    sa.ForeignKeyConstraint(['last_room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_auth_provider', 'users', ['auth_provider'], unique=False)
    op.create_index('idx_users_last_room_id', 'users', ['last_room_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('friends',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('friend_user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'BLOCKED', name='friendstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['friend_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_friends_friend_user_id', 'friends', ['friend_user_id'], unique=False)
    op.create_index('idx_friends_user_id', 'friends', ['user_id'], unique=False)
    op.create_index('uq_friends_pair', 'friends', ['user_id', 'friend_user_id'], unique=True)
    op.create_table('room_roles',
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'EDITOR', 'VISITOR', name='roomroletype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'user_id')
    )
    op.create_index('idx_room_roles_user_id', 'room_roles', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_teams_owner_user_id', 'teams', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_teams_owner_user_id', table_name='teams')
    op.drop_table('teams')
    op.drop_index('idx_room_roles_user_id', table_name='room_roles')
    op.drop_table('room_roles')
    op.drop_index('uq_friends_pair', table_name='friends')
    op.drop_index('idx_friends_user_id', table_name='friends')
    op.drop_index('idx_friends_friend_user_id', table_name='friends')
    op.drop_table('friends')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('idx_users_last_room_id', table_name='users')
    op.drop_index('idx_users_auth_provider', table_name='users')
    op.drop_table('users')
    op.drop_index('uq_room_tiles_position', table_name='room_tiles')
    op.drop_index('idx_room_tiles_room_id', table_name='room_tiles')
    op.drop_index('idx_room_tiles_asset', table_name='room_tiles')
    op.drop_table('room_tiles')
    op.drop_index('idx_room_portals_to_room', table_name='room_portals')
    op.drop_index('idx_room_portals_from_room', table_name='room_portals')
    op.drop_index('idx_room_portals_from_position', table_name='room_portals')
    op.drop_table('room_portals')
    op.drop_index('uq_room_objects_position', table_name='room_objects')
    op.drop_index('idx_room_objects_room_id', table_name='room_objects')
    op.drop_index('idx_room_objects_asset', table_name='room_objects')
    op.drop_table('room_objects')
    op.drop_index('idx_rooms_room_type', table_name='rooms')
    op.drop_index('idx_rooms_owner', table_name='rooms')
    op.drop_index('idx_rooms_is_public', table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
